language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: mvn -U install clean --fail-never --quiet -DskipTests

script:  mvn -U verify --fail-at-end

notifications:
  email:
    on_success: never

matrix:
  fast_finish: true

after_success:
  - ci/deploy-site.sh

