language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: mvn -U verify clean --fail-never --quiet -DskipTests -Dinvoker.skip

script:  mvn -U verify --fail-at-end

notifications:
  email:
    on_success: never

matrix:
  fast_finish: true

after_success:
  - ci/deploy-snapshot.sh
  - ci/deploy-site.sh

sudo: false
cache:
  directories:
    - $HOME/.m2
    - target/it-repo
